CREATE TABLE IF NOT EXISTS `project_proposals` (
  `id` VARCHAR(191) NOT NULL,
  `projectId` VARCHAR(191) NOT NULL,
  `type` VARCHAR(50) NOT NULL,
  `payload` JSON NOT NULL,
  `reason` TEXT NULL,
  `createdByUserId` VARCHAR(191) NOT NULL,
  `approverUserIds` JSON NOT NULL,
  `status` VARCHAR(50) NOT NULL DEFAULT 'PENDING',
  `resolvedByUserId` VARCHAR(191) NULL,
  `resolvedNote` TEXT NULL,
  `expiresAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `project_proposals_projectId_status_createdAt_idx` (`projectId`, `status`, `createdAt`),
  INDEX `project_proposals_projectId_type_status_idx` (`projectId`, `type`, `status`),
  CONSTRAINT `project_proposals_projectId_fkey` FOREIGN KEY (`projectId`) REFERENCES `projects`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `project_proposals_createdByUserId_fkey` FOREIGN KEY (`createdByUserId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `project_proposals_resolvedByUserId_fkey` FOREIGN KEY (`resolvedByUserId`) REFERENCES `users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `project_events` (
  `id` VARCHAR(191) NOT NULL,
  `projectId` VARCHAR(191) NOT NULL,
  `seq` INT NOT NULL,
  `type` VARCHAR(80) NOT NULL,
  `refType` VARCHAR(50) NULL,
  `refId` VARCHAR(191) NULL,
  `payload` JSON NULL,
  `actorUserId` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `project_events_projectId_seq_key` (`projectId`, `seq`),
  INDEX `project_events_projectId_type_createdAt_idx` (`projectId`, `type`, `createdAt`),
  INDEX `project_events_projectId_refType_refId_idx` (`projectId`, `refType`, `refId`),
  CONSTRAINT `project_events_projectId_fkey` FOREIGN KEY (`projectId`) REFERENCES `projects`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `project_events_actorUserId_fkey` FOREIGN KEY (`actorUserId`) REFERENCES `users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `agent_runtimes` (
  `id` VARCHAR(191) NOT NULL,
  `member_id` VARCHAR(191) NULL,
  `provider` VARCHAR(50) NOT NULL,
  `framework` VARCHAR(50) NOT NULL,
  `model` VARCHAR(191) NULL,
  `status` VARCHAR(50) NOT NULL,
  `wake_endpoint` VARCHAR(1000) NULL,
  `metadata` JSON NULL,
  `registered_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `last_seen_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `agent_runtimes_member_id_status_idx` (`member_id`, `status`),
  INDEX `agent_runtimes_framework_status_idx` (`framework`, `status`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `project_access_grants` (
  `id` VARCHAR(191) NOT NULL,
  `project_id` VARCHAR(191) NOT NULL,
  `member_id` VARCHAR(191) NOT NULL,
  `runtime_id` VARCHAR(191) NOT NULL,
  `grant_type` VARCHAR(50) NOT NULL,
  `scopes` JSON NOT NULL,
  `skill_bundle_refs` JSON NULL,
  `status` VARCHAR(50) NOT NULL,
  `reason` TEXT NULL,
  `issued_by_member_id` VARCHAR(191) NULL,
  `issued_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `expires_at` DATETIME(3) NULL,
  `revoked_at` DATETIME(3) NULL,
  `revoked_reason` TEXT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `project_access_grants_project_member_status_idx` (`project_id`, `member_id`, `status`),
  INDEX `project_access_grants_project_runtime_status_idx` (`project_id`, `runtime_id`, `status`),
  INDEX `project_access_grants_project_expires_idx` (`project_id`, `expires_at`),
  CONSTRAINT `project_access_grants_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `project_access_grants_member_id_fkey` FOREIGN KEY (`member_id`) REFERENCES `project_members`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `project_access_grants_runtime_id_fkey` FOREIGN KEY (`runtime_id`) REFERENCES `agent_runtimes`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `participant_presence` (
  `id` VARCHAR(191) NOT NULL,
  `project_id` VARCHAR(191) NOT NULL,
  `member_id` VARCHAR(191) NOT NULL,
  `runtime_id` VARCHAR(191) NULL,
  `presence` VARCHAR(50) NOT NULL,
  `supports_hard_wake` BOOLEAN NOT NULL DEFAULT false,
  `wake_failure_count` INTEGER NOT NULL DEFAULT 0,
  `status_message` TEXT NULL,
  `last_seen_at` DATETIME(3) NULL,
  `last_heartbeat_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `participant_presence_project_member_runtime_key` (`project_id`, `member_id`, `runtime_id`),
  INDEX `participant_presence_project_presence_idx` (`project_id`, `presence`),
  INDEX `participant_presence_project_heartbeat_idx` (`project_id`, `last_heartbeat_at`),
  CONSTRAINT `participant_presence_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `participant_presence_member_id_fkey` FOREIGN KEY (`member_id`) REFERENCES `project_members`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `participant_presence_runtime_id_fkey` FOREIGN KEY (`runtime_id`) REFERENCES `agent_runtimes`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `project_threads` (
  `id` VARCHAR(191) NOT NULL,
  `project_id` VARCHAR(191) NOT NULL,
  `thread_type` VARCHAR(50) NOT NULL,
  `ref_type` VARCHAR(50) NOT NULL,
  `ref_id` VARCHAR(191) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `status` VARCHAR(50) NOT NULL,
  `created_by_member_id` VARCHAR(191) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `project_threads_project_thread_type_idx` (`project_id`, `thread_type`),
  INDEX `project_threads_project_ref_idx` (`project_id`, `ref_type`, `ref_id`),
  INDEX `project_threads_project_status_idx` (`project_id`, `status`),
  CONSTRAINT `project_threads_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `project_messages` (
  `id` VARCHAR(191) NOT NULL,
  `project_id` VARCHAR(191) NOT NULL,
  `thread_id` VARCHAR(191) NOT NULL,
  `sender_member_id` VARCHAR(191) NULL,
  `sender_runtime_id` VARCHAR(191) NULL,
  `message_type` VARCHAR(50) NOT NULL,
  `visibility` VARCHAR(50) NOT NULL,
  `target_member_ids` JSON NULL,
  `mention_member_ids` JSON NULL,
  `body` TEXT NOT NULL,
  `requires_ack` BOOLEAN NOT NULL DEFAULT false,
  `metadata` JSON NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `project_messages_project_thread_created_idx` (`project_id`, `thread_id`, `created_at`),
  INDEX `project_messages_project_sender_idx` (`project_id`, `sender_member_id`),
  CONSTRAINT `project_messages_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `project_messages_thread_id_fkey` FOREIGN KEY (`thread_id`) REFERENCES `project_threads`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `project_inbox_items` (
  `id` VARCHAR(191) NOT NULL,
  `project_id` VARCHAR(191) NOT NULL,
  `target_member_id` VARCHAR(191) NULL,
  `target_runtime_id` VARCHAR(191) NULL,
  `source_member_id` VARCHAR(191) NULL,
  `kind` VARCHAR(50) NOT NULL,
  `owner_action_type` VARCHAR(50) NOT NULL,
  `priority` VARCHAR(20) NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  `wake_hint` VARCHAR(20) NOT NULL,
  `ref_type` VARCHAR(50) NULL,
  `ref_id` VARCHAR(191) NULL,
  `thread_id` VARCHAR(191) NULL,
  `summary` TEXT NOT NULL,
  `details` JSON NULL,
  `superseded_by_inbox_item_id` VARCHAR(191) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `read_at` DATETIME(3) NULL,
  `acked_at` DATETIME(3) NULL,
  `resolved_at` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  INDEX `project_inbox_items_target_member_status_idx` (`project_id`, `target_member_id`, `status`),
  INDEX `project_inbox_items_target_runtime_status_idx` (`project_id`, `target_runtime_id`, `status`),
  INDEX `project_inbox_items_kind_status_idx` (`project_id`, `kind`, `status`),
  INDEX `project_inbox_items_thread_idx` (`project_id`, `thread_id`),
  INDEX `project_inbox_items_created_idx` (`project_id`, `created_at`),
  CONSTRAINT `project_inbox_items_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `project_inbox_items_thread_id_fkey` FOREIGN KEY (`thread_id`) REFERENCES `project_threads`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `project_inbox_items_target_runtime_id_fkey` FOREIGN KEY (`target_runtime_id`) REFERENCES `agent_runtimes`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `project_inbox_items_superseded_by_fkey` FOREIGN KEY (`superseded_by_inbox_item_id`) REFERENCES `project_inbox_items`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `external_links` (
  `id` VARCHAR(191) NOT NULL,
  `project_id` VARCHAR(191) NOT NULL,
  `ref_type` VARCHAR(50) NOT NULL,
  `ref_id` VARCHAR(191) NOT NULL,
  `external_type` VARCHAR(50) NOT NULL,
  `external_id` VARCHAR(191) NOT NULL,
  `external_url` VARCHAR(1000) NOT NULL,
  `metadata` JSON NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `external_links_type_id_key` (`external_type`, `external_id`),
  INDEX `external_links_project_ref_idx` (`project_id`, `ref_type`, `ref_id`),
  CONSTRAINT `external_links_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `external_events` (
  `id` VARCHAR(191) NOT NULL,
  `project_id` VARCHAR(191) NOT NULL,
  `source` VARCHAR(50) NOT NULL,
  `external_event_id` VARCHAR(191) NOT NULL,
  `kind` VARCHAR(80) NOT NULL,
  `linked_work_item_id` VARCHAR(191) NULL,
  `mapped_project_event_id` VARCHAR(191) NULL,
  `payload` JSON NOT NULL,
  `received_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `external_events_source_event_key` (`source`, `external_event_id`),
  INDEX `external_events_project_kind_received_idx` (`project_id`, `kind`, `received_at`),
  INDEX `external_events_project_work_item_idx` (`project_id`, `linked_work_item_id`),
  CONSTRAINT `external_events_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `external_events_linked_work_item_id_fkey` FOREIGN KEY (`linked_work_item_id`) REFERENCES `project_work_items`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `external_events_mapped_event_id_fkey` FOREIGN KEY (`mapped_project_event_id`) REFERENCES `project_events`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
